### ISSUE TITLE
Not an Issue but:

### ISSUE THREAD

**Issue by francotheengineer** [philipperemy/tensorflow-grid-lstm#1]
Hi Philip,

Just reading through your code base. Funnily enough, my code looks exactly like yours.. I upgraded Hunkim's word rnn to the lastest TF functions. Did you do the same?  It looks like we both make Hunkim's code more concise. 

Franco

**Comment by philipperemy** [comment]
I've used the official TF upgrade python script. So I guess there's mainly one way to do the things correctly :)

**Comment by francotheengineer** [comment]
hummm... well I just spent a week doing so! didn't know the script was so good. I'm just pushing my self to learn ML. Thanks for code, you've got some great repos. (Y)

**Comment by philipperemy** [comment]
Thanks a lot! I appreciate! Good luck with your ML study!
